export const emojiDictionary = {
    "😀": "Grinning Face",
    "😃": "Grinning Face with Big Eyes",
    "😄": "Grinning Face with Smiling Eyes",
    "😁": "Beaming Face with Smiling Eyes",
    "😆": "Grinning Squinting Face",
    "😅": "Grinning Face with Sweat",
    "🤣": "Rolling on the Floor Laughing",
    "😂": "Face with Tears of Joy",
    "🙂": "Slightly Smiling Face",
    "🙃 ": "Upside-Down Face",
    "😉": "Winking Face",
    "😊": "Smiling Face with Smiling Eyes",
    "😇": "Smiling Face with Halo",
    "🥰": "Smiling Face with Hearts",
    "😍": "Smiling Face with Heart-Eyes",
    "🤩": "Star-Struck",
    "😘": "Face Blowing a Kiss",
    "😗": "Kissing Face",
    "😚": "Kissing Face with Closed Eyes",
    "😙": "Kissing Face with Smiling Eyes",
    "🥲": "Smiling Face with Tear",
    "😋": "Face Savoring Food",
    "😛": "Face with Tongue",
    "😜": "Winking Face with Tongue",
    "🤪": "Zany Face",
    "😝": "Squinting Face with Tongue",
    "🤑": "Money-Mouth Face",
    "🤗": "Hugging Face",
    "🤭": "Face with Hand Over Mouth",
    "🤫": "Shushing Face",
    "🤔": "Thinking Face",
    "🤐": "Zipper-Mouth Face",
    "🤨": "Face with Raised Eyebrow",
    "😐": "Neutral Face",
    "😑": "Expressionless Face",
    "😶": "Face Without Mouth",
    "😶‍🌫️": "Face in Clouds",
    "😏": "Smirking Face",
    "😒": "Unamused Face",
    "😬": "Grimacing Face",
    "🙄": "Face with Rolling Eyes",
    "😮‍💨": "Face Exhaling",
    "🤥": "Lying Face",
    "😌": "Relieved Face",
    "😔": "Pensive Face",
    "😪": "Sleepy Face",
    "🤤": "Drooling Face",
    "😴": "Sleeping Face",
    "😷": "Face with Medical Mask",
    "🤒": "Face with Thermometer",
    "🤕": "Face with Head-Bandage",
    "🤢": "Nauseated Face",
    "🤮": "Face Vomiting",
    "🤧": "Sneezing Face",
    "🥵": "Hot Face",
    "🥶": "Cold Face",
    "🥴": "Woozy Face",
    "😵": "Dizzy Face",
    "😵‍💫 ": "Face with Spiral Eyes",
    "🤯": "Exploding Head",
    "🤠": "Cowboy Hat Face",
    "🥸": "Disguised Face",
    "😎": "Smiling Face with Sunglasses",
    "🤓": "Nerd Face",
    "🧐": "Face with Monocle",
    "😕": "Confused Face",
    "😟": "Worried Face",
    "🙁": "Slightly Frowning Face",
    "😮": "Face with Open Mouth",
    "😯": "Hushed Face",
    "😲": "Astonished Face",
    "😳": " Flushed Face",
    "🥺": "Pleading Face",
    "😦": " Frowning Face with Open Mouth",
    "😧": "Anguished Face",
    "😨": "Fearful Face",
    "😰": "Anxious Face with Sweat",
    "😥": "Sad but Relieved Face",
    "😢": "Crying Face",
    "😱": "Face Screaming in Fear",
    "😭": "Loudly Crying Face",
    "😖": "Confounded Face",
    "😣": "Persevering Face",
    "😞": "Disappointed Face",
    "😓": " Downcast Face with Sweat",
    "😩": "Weary Face",
    "😫": "Tired Face",
    "🥱": "Yawning Face",
    "😤": "Face with Steam From Nose",
    "😡": "Pouting Face",
    "😠": "Angry Face",
    "🤬": "Face with Symbols on Mouth",
    "😈": " Smiling Face with Horns",
    "👿": " Angry Face with Horns",
    "💀": "Skull",
    "💩": "Pile of Poo",
    "🤡": "Clown Face",
    "👹": "Ogre",
    "👺": " Goblin",
    "👻": "Ghost",
    "👽": "Alien",
    "👾": "Alien Monster",
    "🤖": "Robot",
    "😺": "Grinning Cat",
    "😸": "Grinning Cat with Smiling Eyes",
    "😹": "Cat with Tears of Joy",
    "😻": "Smiling Cat with Heart-Eyes",
    "😼": " Cat with Wry Smile",
    "😽": " Kissing Cat",
    "🙀": " Weary Cat",
    "😿": " Crying Cat",
    "😾": " Pouting Cat",
    "💋 ": "Kiss Mark",
    "👋 ": "Waving Hand",
    "🤚 ": "Raised Back of Hand",
    "🖐️": " Hand with Fingers Splayed",
    "✋": " Raised Hand",
    "🖖": " Vulcan Salute",
    "👌": "OK Hand",
    "🤌 ": "Pinched Fingers",
    "🤏 ": "Pinching Hand",
    "🤞": " Crossed Finger,s",
    "🤟": " Love-You Gesture",
    "🤘 ": "Sign of the Horns",
    "🤙": "  Call Me Hand",
    "👈": "Backhand Index Pointing Left",
    "👉": "Backhand Index Pointing Right",
    "👆": " Backhand Index Pointing Up",
    "🖕": "Middle Finger",
    "👇": "Backhand Index Pointing Down",
    "☝": "Index Pointing Up",
    "👍": " Thumbs Up",
    "👎": " Thumbs Down",
    "✊": "Raised Fist",
    "👊": " Oncoming Fist",
    "🤛": " Left-Facing Fist",
    "🤜": " Right-Facing Fist",
    "👏": "Clapping Hands",
    "🙌": "Raising Hands",
    "👐": "Open Hands",
    "🤲": "Palms Up Together",
    "🤝": "Handshake",
    "🙏": "Folded Hands",
    "✍️": "Writing Hand",
    "💅 ": "Nail Polish",
    "🤳": "Selfie",
    "💪": "Flexed Biceps",
    "🦵": "Leg",
    "🦶": " Foot",
    "👂": "Ear",
    "🦻 ": "Ear with Hearing Aid",
    "👃": " Nose",
    "🧠": "Brain",
    "🦷 ": "Tooth",
    "🦴 ": "Bone",
    "👀 ": "Eyes",
    "👁️": " Eye",
    "👅": " Tongue",
    "👄 ": "Mouth",
    "👶": "Baby",
    "🧒": "Child",
    "👦": " Boy",
    "👧": "Girl",
    "🧑": "Person",
    "👱": "Person Blond Hair",
    "👨": "Man",
    "🧔": " Person Beard",
    "👨‍🦰 ": "Man Red Hair",
    "👨‍🦱": " Man Curly Hai",
    "🙅‍♂️": "Man Gesturing No",
    "🙆": "Person Gesturing OK",
    "🙆‍♂️": "Man Gesturing OK",
    "🙆‍♀️": "Woman Gesturing OK",
    "💁": "Person Tipping Hand",
    "💁‍♂️": " Man Tipping Hand",
    "💁‍♀️": "Woman Tipping Hand",
    "🙋 ": "Person Raising Hand",
    "🙋‍♂️": "Man Raising Hand",
    "🙋‍♀️": "Woman Raising Hand",
    "🧏": "Deaf Person",
    "🩳": "Shorts",
    "👙": " Bikini",
    "👛": "Purse",
    "👜": " Handbag",
    "👝": "Clutch Bag",
    "🎒": "Backpack",
    "👞 ": "Man’s Shoe",
    "👟 ": "Running Shoe",
    "🥾 ": "Hiking Boot",
    "🥿": " Flat Shoe",
    "👠": "High-Heeled Shoe",
    "👡": " Woman’s Sandal",
    "🩰": " Ballet Shoes",
    "👢": "Woman’s Boot",
    "👑": " Crown",
    "👒": "Woman’s Hat",
    "🎩": " Top Hat",
    "🎓": "Graduation Cap",
    "🧢": "Billed Cap",
    "⛑️": " Rescue Worker’s Helmet",
    "💄": " Lipstick",
    "💍": "Ring",
    "💼": " Briefcase",
    "🩸": "Drop of Blood"
  };